export default  menuItems = [
    "Edit Profile",
    "Notifications",
    "Privacy",
    "Security",
    "Change Password",
    "Language",
    "Appearance",
    "Help Center",
    "Contact Support",
    "Terms of Service",
    "About App",
    "App Version",
    "Backup Data",
    "Sync Settings",
    "Connected Devices",
    "Delete Account",
    "Logout",
];